tap "bfontaine/utils"
tap "bufbuild/buf"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "tkomatsu/pbit"
brew "anyenv"
brew "automake"
brew "bash"
brew "bat"
brew "binutils"
brew "python@3.9"
brew "glib"
brew "cairo"
brew "gmp"
brew "cask"
brew "clang-format"
brew "cloc"
brew "cmake"
brew "php", link: false
brew "composer"
brew "docker", link: false
brew "dosfstools"
brew "exa"
brew "exiftool"
brew "gobject-introspection"
brew "harfbuzz"
brew "libass"
brew "srt"
brew "ffmpeg"
brew "figlet"
brew "mpfr"
brew "gcc"
brew "gh"
brew "git"
brew "go"
brew "pango"
brew "graphviz"
brew "groonga"
brew "hugo"
brew "i386-elf-gdb"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "mariadb"
brew "mas"
brew "minikube"
brew "mpc"
brew "nasm"
brew "nghttp2"
brew "openjdk@11"
brew "pandoc"
brew "php@8.0", link: true
brew "plantuml"
brew "postgresql"
brew "qemu"
brew "reattach-to-user-namespace"
brew "ruby-build"
brew "shellcheck"
brew "siege"
brew "starship"
brew "telnet"
brew "tmux"
brew "tnftp"
brew "vim"
brew "wget"
brew "zsh"
brew "bfontaine/utils/rfc"
brew "bufbuild/buf/buf"
brew "heroku/brew/heroku"
brew "tkomatsu/pbit/pbit"
cask "deepl"
cask "discord"
cask "docker"
cask "firefox"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "keepingyouawake"
cask "notion"
cask "owasp-zap"
cask "postman"
cask "slack"
cask "stoplight-studio"
cask "tableplus"
cask "visual-studio-code"
cask "wireshark"
cask "xquartz"
cask "zoom"
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "RunCat", id: 1429033973
